#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define POWER_CHARGE_DETECT_PIN GPIO_NUM_21
#define POWER_ADC_UNIT ADC_UNIT_2
#define POWER_ADC_CHANNEL ADC_CHANNEL_3

// Dog-style servo pin mapping (5 servos) - Fixed for ESP32S3 compatibility
#define DOG_LEFT_FRONT_PIN GPIO_NUM_17   // Left Front leg - Free GPIO
#define DOG_RIGHT_FRONT_PIN GPIO_NUM_18   // Right Front leg - Free GPIO  
#define DOG_LEFT_BACK_PIN GPIO_NUM_8     // Left Back leg - Changed from GPIO 39 (input-only)
#define DOG_RIGHT_BACK_PIN GPIO_NUM_38   // Right Back leg - OK for output
#define DOG_TAIL_PIN GPIO_NUM_39         // Tail servo - ESP32-S3 GPIO 39 can be output

// Legacy compatibility for existing code
#define LEFT_LEG_PIN DOG_LEFT_FRONT_PIN
#define RIGHT_LEG_PIN DOG_RIGHT_FRONT_PIN
#define LEFT_FOOT_PIN DOG_LEFT_BACK_PIN
#define RIGHT_FOOT_PIN DOG_RIGHT_BACK_PIN


#define AUDIO_INPUT_SAMPLE_RATE 16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#define AUDIO_I2S_METHOD_SIMPLEX

#define AUDIO_I2S_MIC_GPIO_WS GPIO_NUM_4
#define AUDIO_I2S_MIC_GPIO_SCK GPIO_NUM_5
#define AUDIO_I2S_MIC_GPIO_DIN GPIO_NUM_6
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_7
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_15
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_16

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_3
#define DISPLAY_MOSI_PIN GPIO_NUM_10
#define DISPLAY_CLK_PIN GPIO_NUM_9
#define DISPLAY_DC_PIN GPIO_NUM_46
#define DISPLAY_RST_PIN GPIO_NUM_11
#define DISPLAY_CS_PIN GPIO_NUM_NC

#define LCD_TYPE_ST7789_SERIAL
#define DISPLAY_WIDTH 240
#define DISPLAY_HEIGHT 240
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR true
#define DISPLAY_RGB_ORDER LCD_RGB_ELEMENT_ORDER_RGB
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 3

#define BOOT_BUTTON_GPIO GPIO_NUM_0

// TTP223 touch sensor GPIO (active HIGH on touch)
// Connect TTP223 OUT to this pin, VCC to 3.3V, GND to GND
// Changed from GPIO 2 to GPIO 12
#define TOUCH_TTP223_GPIO GPIO_NUM_12

#define OTTO_ROBOT_VERSION "1.4.7"

#endif  // _BOARD_CONFIG_H_
